### ISSUE TITLE
As a reader, I want to comment in each post. So that i can give feedback to the post for admin

### ISSUE THREAD

**Issue by Ngdaz** [huyhandes/USTH-SE-2019#16]

**Comment by Ngdaz** [comment]
### **Task list**

- [x] Check the INVEST rule for this item.
- [ ] Design form for this funtion using HTML
- [ ] Making Button (comment)
- [ ] Make Database 
- [ ] Connect Database with back-end 
- [ ] Test this function with tester on 3 type device 
- [ ] make list of error and find solution for it
