### ISSUE TITLE
As a page manager, I want to edit posted review button  so that my page can constantly updated

### ISSUE THREAD

**Issue by Ngdaz** [huyhandes/USTH-SE-2019#18]

**Comment by Ngdaz** [comment]
### **Task list**

- [x] check INVEST rule for this issue 
- [x] Design the edit button [source](https://github.com/huyhandes/USTH-SE-2019/blob/master/Group6/views/submitform.hbs)
- [x] Design Ui [source](https://github.com/huyhandes/USTH-SE-2019/blob/master/Group6/views/submitform.hbs)
- [x] Meet Tester , make some test 
- [x] Analize the result after testing, do some discussion then set solution for those issues
